# playbook to deploy wordpress LAMP stack onto EC2 ubuntu
# Created By: Sumanth

---

- hosts: wordpress
  become: true
  gather_facts: no
  tasks: 
  - name: execute sample script
    script: appscript.sh
    register: diskusage

  - debug: var=diskusage
